### ISSUE TITLE
Use mono fonts for results pane

### ISSUE THREAD

**Issue by cangyin** [lodthe/clickhouse-playground#24]
Using mono fonts would be nicer for text aligning.

![image](https://user-images.githubusercontent.com/50256182/218411386-4e3710c3-5f99-43e3-8d97-613f12e11360.png)

**Comment by lodthe** [comment]
Hmm, the font family is `Roboto Mono, monospace`. Probably, there are some issues with the support of this font in some browsers. Anyway, it looks nearly _ugly_ on your screen, so the design has to be changed.

There are short-term plans to enable SQL highlight and update the fonts in the text fields. I will check whether mono fonts will work after the update.

Could you please provide information about your browser name and version?

**Comment by cangyin** [comment]
chrome 110.0.5481.104

**Comment by lodthe** [comment]
I've updated the code editor and output viewer, and now a monospace font should be used:

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/4996880/224565411-2dc7f261-215a-43bb-b20f-72dad890bba4.png">

**Comment by cangyin** [comment]
looks great !
