### ISSUE TITLE
Error “The string did not match the expected pattern”

### ISSUE THREAD

**Issue by elcolex777** [lodthe/clickhouse-playground#41]
При использовании запроса
`select substr('abc',1,1) `
в окне результата появляется ошибка «The string did not match the expected pattern.».

Не нравится название функции substr. Если ее назвать по-другом, например, так:
`select xsubstr('abc',1,1) `
, то выдается сообщение об ошибке из кликхаус (что, собственно, и должно быть).

ссылка на фиддл:
https://fiddle.clickhouse.com/30e2a527-833c-4ccc-90f7-26e73b6a6878
(там «нормальный» sql, нужно просто удалить символ “x” из названия. С функцией substr не смог сделать, урл в адресной строке не меняется))

вот скрин.
![IMG_4988](https://github.com/lodthe/clickhouse-playground/assets/140021099/564567a1-1bbd-4545-8daf-2901f0bd330e)

Использую iPad, браузер Safari.

**Comment by lodthe** [comment]
Для clickhouse.com включили слишком агрессивную защиту от SQL инъекций. Спасибо, разберемся.
